#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flameshot
Version  : 0.6.0
Release  : 2
URL      : https://github.com/lupoDharkael/flameshot/archive/v0.6.0.tar.gz
Source0  : https://github.com/lupoDharkael/flameshot/archive/v0.6.0.tar.gz
Summary  : Powerful yet simple to use screenshot software
Group    : Development/Tools
License  : Apache-2.0 GPL-3.0
BuildRequires : buildreq-qmake
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5DBus)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : qttools-dev

%description
Flameshot is a screenshot software, it's
powerful yet simple to use for GNU/Linux

%prep
%setup -q -n flameshot-0.6.0
cd %{_builddir}/flameshot-0.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
%qmake QMAKE_CFLAGS+=-fno-lto QMAKE_CXXFLAGS+=-fno-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1586855544
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
